server:
  port: 8000
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:9000}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks