spring:
  # database config
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:oauth2}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      authorizationserver:
        client:
          coachcore-web-app:
            registration:
              client-id: ${OAUTH2_WEB_APP_CLIENT_ID:coachcore-web-app}
              client-secret: ${OAUTH2_WEB_APP_CLIENT_SECRET}
              client-authentication-methods:
                - "client_secret_basic" 
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - ${OAUTH2_WEB_APP_CLIENT_REDIRECT_URI:http://localhost:3000}  
              scopes:
                - "openid"
          coachcore-mail-sender:
            registration:
              client-id: ${OAUTH2_MAIL_CLIENT_ID:coachcore-mail-sender}
              client-secret: ${OAUTH2_MAIL_CLIENT_SECRET}
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "mail.send" 
            
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
server:
  port: 9000

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
issuer: ${ISSUER:http://localhost:9000}
admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
  email: ${ADMIN_EMAIL}
