server:
  port: 9001
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          auth-server:
#            client-id: shapeit
#            client-secret: shapeit
#        provider:
#          auth-server:
#            issuer-uri: http://localhost:9000