spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5433}/${DB_NAME:newsletter}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          mail-client:
            provider: coachcore
            client-id: ${OAUTH2_MAIL_CLIENT_ID:coachcore-mail-sender}
            client-secret: ${OAUTH2_MAIL_CLIENT_SECRET:mail-sender-secret}
            authorization-grant-type: client_credentials
            scope: mail.send
        provider:
          coachcore:
            token-uri: ${AUTHORIZATION_SERVER_HOST:http://localhost:9000}${TOKEN_URI:/oauth2/token}
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVER_HOST:http://localhost:9000}
          jwk-set-uri: ${AUTHORIZATION_SERVER_HOST:http://localhost:9000}${JWKS_SET_URI:/oauth2/jwks}
logging:
  level:
    org:
      springframework:
        security: ${LOGGING_LEVEL:INFO}
    pro:
      coachcore: ${LOGGING_LEVEL:INFO}
server:
  port: 8001
email-service:
  url: ${EMAIL_SERVICE_URL:http://localhost:8083}