spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:shapeit-api}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:9000}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks
logging:
  level:
    org:
      springframework:
        security: DEBUG
oauth2-mail-client:
  client-id: ${OAUTH2_MAIL_CLIENT_ID}
  client-secret: ${OAUTH2_MAIL_CLIENT_SECRET}
server:
  port: 8000