version: "3.9"

services:
  oauth2-db:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSRGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:
  newsletter-db:
    image: postgres:16.2
    ports:
      - 5433:5432
    environment:
      POSRGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsletter
  training-db:
    image: postgres:16.2
    ports:
      - 5434:5432
    environment:
      POSRGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: training
