version: "version"
services:
  gateway:
    image: ghcr.io/coachcore/gateway:0.0.3
    ports:
      - 8080:8080
    environment:
      OAUTH2_SERVER_URL: http://oauth2-server:9000
      TRAINING_SERVICE_URL: http://training-service:8082
      LOGGING_LEVEL: DEBUG
    depends_on:
      - oauth2-server
      - training-service
  training-db:
    image: postgres:16.2
    ports:
      - 5434:5432
    environment:
      POSRGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: training
  training-service:
    image: ghcr.io/coachcore/training-api:1.4.0
    environment:
      DB_HOST: training-db:5432
      AUTH_SERVER_HOST: http://oauth2-server:9000
      LOGGING_LEVEL: DEBUG
    depends_on:
      - training-db
      - oauth2-server
  oauth2-db:
    image: postgres:16.2
    ports:
      - 5433:5432
    environment:
      POSRGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oauth2
  oauth2-server:
    image: ghcr.io/coachcore/oauth2-server:0.0.5
    ports:
      - 9000:9000
    environment:
      DB_HOST: oauth2-db:5432
      DB_NAME: oauth2
      ISSUER: http://oauth2-server:9000
      OAUTH2_WEB_APP_CLIENT_SECRET: $$2a$$10$$vLW8gLjoVpksEJf70SGPAOUd1H.ppsIgFTQbU63HVyXDaAcvcZuMe
      LOGGING_LEVEL: DEBUG
    depends_on:
      - oauth2-db
